[versions]
sdk-compile = "34"
sdk-min = "21"
sdk-target = "33"

# Must be updated along with plugin-compose-jetbrains
compose-bom = "2023.06.01"
compose-compiler = "1.5.1"
accompanist = "0.30.1"
activity-compose = "1.7.2"

plugin-compose-jetbrains = "1.4.3"
plugin-android-gradle = "8.1.0"
plugin-kotlin = "1.9.0"
plugin-detekt = "1.21.0"
plugin-spotless = "6.5.1"
plugin-mavenpublish = "0.25.3"

java-jvmTarget = "1.8"
java-sourceCompatibility = "1.8"
java-targetCompatibility = "1.8"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uitoolingpreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-activitycompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-android-gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "plugin-compose-jetbrains" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "plugin-kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "plugin-detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "plugin-spotless" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "plugin-mavenpublish" }
